package com.citi.argentina.ip.gpservice.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
/*
 * import lombok.AllArgsConstructor; import lombok.Getter; import lombok.NoArgsConstructor; import lombok.Setter;
 */

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/*@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor*/
@Document(collection = "account")
public class Account {

	@Id
	private String id; //primary key
	private String acctId; //CITI{123456}-autogenerated in create method, index should be in this in mongodb
	private String acctName;
	private BankDetails bankDetails; // bankId,bankName,IFSC,branchCode
	private Contacts contacts; //contact number and email
	private Address addressDetails; //address1,2,city,state,landmark,zip
	private Float amount;
	private String accountType; //savings,current,loan
	private String status; //true false
	private Audit audit; //createdby, createdDate, modifyBy, modifiedDate

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getAcctId() {
		return acctId;
	}

	public void setAcctId(String acctId) {
		this.acctId = acctId;
	}

	public String getAcctName() {
		return acctName;
	}

	public void setAcctName(String acctName) {
		this.acctName = acctName;
	}

	public BankDetails getBankDetails() {
		return bankDetails;
	}

	public void setBankDetails(BankDetails bankDetails) {
		this.bankDetails = bankDetails;
	}

	public Contacts getContacts() {
		return contacts;
	}

	public void setContacts(Contacts contacts) {
		this.contacts = contacts;
	}

	public Address getAddressDetails() {
		return addressDetails;
	}

	public void setAddressDetails(Address addressDetails) {
		this.addressDetails = addressDetails;
	}

	public Float getAmount() {
		return amount;
	}

	public void setAmount(Float amount) {
		this.amount = amount;
	}

	public String getAccountType() {
		return accountType;
	}

	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Audit getAudit() {
		return audit;
	}

	public void setAudit(Audit audit) {
		this.audit = audit;
	}

	public Account() {
	}

	public Account(String id, String acctId, String acctName, BankDetails bankDetails, Contacts contacts, Address addressDetails, Float amount, String accountType, String status, Audit audit) {
		this.id = id;
		this.acctId = acctId;
		this.acctName = acctName;
		this.bankDetails = bankDetails;
		this.contacts = contacts;
		this.addressDetails = addressDetails;
		this.amount = amount;
		this.accountType = accountType;
		this.status = status;
		this.audit = audit;
	}
}
